# Generated by Django 5.1.3 on 2024-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_archivo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("waiting_close", "Waiting for Close"),
                    ("waiting_archive", "Waiting for Archive"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("archive_responsible", "Archive Responsible"),
                    ("admin", "System Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
