# Generated by Django 5.1.3 on 2024-12-05 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universe',
            name='description',
        ),
        migrations.AddField(
            model_name='universe',
            name='name',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='universe',
            name='doc_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='BoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('new', 'New Box'), ('change_area', 'Change of Area'), ('doc_added', 'Document Added')], max_length=20)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('observations', models.TextField(blank=True, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('area_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_logs', to='gestion_archivo_app.area')),
                ('area_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_logs', to='gestion_archivo_app.area')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='gestion_archivo_app.box')),
                ('doc_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_added', to='gestion_archivo_app.documentation')),
                ('doc_removed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_removed', to='gestion_archivo_app.documentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_logs', to='gestion_archivo_app.area')),
            ],
        ),
        migrations.DeleteModel(
            name='BoxMovement',
        ),
    ]
