# Generated by Django 5.1.3 on 2024-12-16 15:08

import django.db.models.deletion
import gestion_archivo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='is_deposit',
            field=models.BooleanField(default=False, verbose_name='Is Deposit'),
        ),
        migrations.AlterField(
            model_name='box',
            name='destruction_year',
            field=models.PositiveSmallIntegerField(verbose_name='Destruction Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deposit',
            field=models.ForeignKey(default=gestion_archivo_app.models.get_default_archive, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='gestion_archivo_app.area', verbose_name='Archive'),
        ),
    ]
