# Generated by Django 5.1.3 on 2024-12-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0002_alter_box_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlog',
            name='area_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_logs', to='gestion_archivo_app.area'),
        ),
        migrations.AlterField(
            model_name='boxlog',
            name='area_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_logs', to='gestion_archivo_app.area'),
        ),
    ]
