# Generated by Django 5.1.3 on 2024-12-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_archivo_app",
            "0002_remove_universe_description_universe_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="total_sheets",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
