# Generated by Django 5.1.3 on 2024-12-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0003_alter_boxlog_area_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('waiting_close', 'Waiting for Close'), ('waiting_archive', 'Waiting for Archive'), ('accepted_archive', 'Accepted by Archive Responsible'), ('archived', 'In Archive')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='boxlog',
            name='log_type',
            field=models.CharField(choices=[('new', 'New Box'), ('change_area', 'Change of Area'), ('doc_added', 'Document Added'), ('doc_removed', 'Document Removed'), ('doc_edited', 'Document Edited'), ('status_change', 'Status Changed'), ('area_change', 'Area Changed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentations', to='gestion_archivo_app.box'),
        ),
    ]
