# Generated by Django 5.1.3 on 2024-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0003_box_total_sheets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('manager', 'Manager'), ('archive_responsible', 'Archive Responsible'), ('admin', 'System Administrator')], max_length=20),
        ),
    ]
