# Generated by Django 5.1.3 on 2024-12-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_archivo_app", "0003_alter_box_destruction_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("archive_responsible", "Archive Responsible"),
                    ("admin", "System Administrator"),
                ],
                max_length=32,
            ),
        ),
    ]
