# Generated by Django 5.1.3 on 2024-12-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemConfig',
            new_name='SystemConfigKeyValues',
        ),
    ]
