# Generated by Django 5.1.3 on 2024-12-18 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_archivo_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlog',
            name='area_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_logs', to='gestion_archivo_app.area'),
        ),
        migrations.AlterField(
            model_name='boxlog',
            name='area_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_logs', to='gestion_archivo_app.area'),
        ),
        migrations.AlterField(
            model_name='boxlog',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gestion_archivo_app.box'),
        ),
        migrations.AlterField(
            model_name='boxlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
